const personas = [
  {
    id: 1,
    first_name: "Kelsy",
    email: "kphilson0@instagram.com",
    gender: "Bigender",
  },
  {
    id: 2,
    first_name: "Fraser",
    email: "fseiter1@xinhuanet.com",
    gender: "Female",
  },
  {
    id: 3,
    first_name: "Annabelle",
    email: "abartolic2@mail.ru",
    gender: "Bigender",
  },
  {
    id: 4,
    first_name: "Pier",
    email: "pballefant3@bloglovin.com",
    gender: "Genderfluid",
  },
  {
    id: 5,
    first_name: "Yorgos",
    email: "yfarny4@accuweather.com",
    gender: "Bigender",
  },
  {
    id: 6,
    first_name: "Randy",
    email: "rprawle5@google.com.au",
    gender: "Male",
  },
  {
    id: 7,
    first_name: "Dukey",
    email: "dharvey6@blogs.com",
    gender: "Genderqueer",
  },
  {
    id: 8,
    first_name: "Corina",
    email: "ctonnesen7@epa.gov",
    gender: "Non-binary",
  },
  {
    id: 9,
    first_name: "Adan",
    email: "aesposito8@ihg.com",
    gender: "Non-binary",
  },
  {
    id: 10,
    first_name: "Donnie",
    email: "dwarrior9@about.me",
    gender: "Genderfluid",
  },
  {
    id: 11,
    first_name: "Hermy",
    email: "hlayinga@ox.ac.uk",
    gender: "Genderqueer",
  },
  { id: 12, first_name: "Tami", email: "tmoreb@globo.com", gender: "Female" },
  { id: 13, first_name: "Gerri", email: "gtillardc@icq.com", gender: "Female" },
  {
    id: 14,
    first_name: "Kendra",
    email: "korgand@businessinsider.com",
    gender: "Bigender",
  },
  {
    id: 15,
    first_name: "Gill",
    email: "gskedgee@stumbleupon.com",
    gender: "Genderfluid",
  },
  {
    id: 16,
    first_name: "Nancee",
    email: "nbrechinf@reuters.com",
    gender: "Female",
  },
  {
    id: 17,
    first_name: "Gert",
    email: "gdiddamsg@nbcnews.com",
    gender: "Bigender",
  },
  {
    id: 18,
    first_name: "Kimbra",
    email: "kcopnerh@hhs.gov",
    gender: "Genderqueer",
  },
  {
    id: 19,
    first_name: "Creighton",
    email: "churlstoni@ocn.ne.jp",
    gender: "Polygender",
  },
  {
    id: 20,
    first_name: "Drusy",
    email: "dkinnachj@apache.org",
    gender: "Agender",
  },
];
