const personas = [
  {
    id: 1,
    first_name: "Enrika",
    email: "epoxton0@edublogs.org",
    gender: "Agender",
  },
  {
    id: 2,
    first_name: "Jenine",
    email: "jchaloner1@i2i.jp",
    gender: "Bigender",
  },
  {
    id: 3,
    first_name: "Orland",
    email: "oblakes2@senate.gov",
    gender: "Genderfluid",
  },
  { id: 4, first_name: "Cy", email: "csparrowe3@google.ca", gender: "Agender" },
  {
    id: 5,
    first_name: "Desiri",
    email: "ddumbar4@oracle.com",
    gender: "Agender",
  },
  {
    id: 6,
    first_name: "Chancey",
    email: "cbreeder5@mac.com",
    gender: "Polygender",
  },
  {
    id: 7,
    first_name: "Philippine",
    email: "pderx6@tinypic.com",
    gender: "Bigender",
  },
  {
    id: 8,
    first_name: "Dix",
    email: "dthomtson7@symantec.com",
    gender: "Bigender",
  },
  { id: 9, first_name: "Barr", email: "bhynam8@usnews.com", gender: "Agender" },
  {
    id: 10,
    first_name: "Horatia",
    email: "hbubb9@histats.com",
    gender: "Polygender",
  },
  {
    id: 11,
    first_name: "Pren",
    email: "pinnetta@springer.com",
    gender: "Female",
  },
  {
    id: 12,
    first_name: "Thaxter",
    email: "tbonfieldb@biblegateway.com",
    gender: "Bigender",
  },
  {
    id: 13,
    first_name: "Nigel",
    email: "nludyc@microsoft.com",
    gender: "Female",
  },
  {
    id: 14,
    first_name: "Mandie",
    email: "mralphsd@liveinternet.ru",
    gender: "Genderqueer",
  },
  {
    id: 15,
    first_name: "Alysa",
    email: "afeatherbiee@is.gd",
    gender: "Female",
  },
  {
    id: 16,
    first_name: "Flory",
    email: "fmallochf@yale.edu",
    gender: "Genderfluid",
  },
  {
    id: 17,
    first_name: "Jacinthe",
    email: "jlomanseyg@jalbum.net",
    gender: "Bigender",
  },
  {
    id: 18,
    first_name: "Claribel",
    email: "cyessonh@e-recht24.de",
    gender: "Polygender",
  },
  {
    id: 19,
    first_name: "Elyse",
    email: "edziwiszi@toplist.cz",
    gender: "Polygender",
  },
  {
    id: 20,
    first_name: "Anica",
    email: "ahughesdonj@telegraph.co.uk",
    gender: "Genderqueer",
  },
];
